name: Feature Workflow

on:
    push:
        branches: ["feature/**"]

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src
    
    unit_test:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests
    
    integration_test:
        name: Integration Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

    create_pr:
      name: Create Pull Request
      runs-on: ubuntu-latest
      needs: [unit_test, integration_test]
      steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @actions/github axios

      - name: Create Pull Request To Develop
        run: |
          TOKEN="${{ secrets.GITHUB_TOKEN }}"
          BASE="develop"
          FEATURE_BRANCH=$(echo "${GITHUB_REF}" | sed -E 's/refs\/heads\/(.+)/\1/')
          TITLE="Automatically generated PR from ${FEATURE_BRANCH} to ${BASE}"
          BODY="Automatically generated PR for branch ${FEATURE_BRANCH} to ${BASE}."

          URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls"
          RESPONSE=$(curl -X POST -sSL -H "Authorization: token ${TOKEN}" -H "Content-Type: application/json" -d "{\"title\":\"${TITLE}\",\"body\":\"${BODY}\",\"head\":\"${FEATURE_BRANCH}\",\"base\":\"${BASE}\"}" "${URL}")

          echo "PR created: ${RESPONSE}"