name: Feature Workflow

on:
    push:
        branches: ["feature/**"]

permissions:
    contents: write

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src
    
    unit_test:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests
    
    integration_test:
        name: Integration Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'

            - name: Restore dependencies
              run: dotnet restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

            - name: Build test project
              run: dotnet build --no-restore
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

            - name: Run tests
              run: dotnet test --verbosity normal
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

    create_pr:
      name: Create Pull Request
      runs-on: ubuntu-latest
      needs: [unit_test, integration_test]
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            ref: ${{github.head_ref}}

        - name: Setup Git
          run: |
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        - name: Create and Push Branch
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            BRANCH_NAME=auto-pr-branch-${{ github.sha }}
            git checkout -b $BRANCH_NAME ${{github.head_ref}}
            git push origin $BRANCH_NAME
        
        - name: Check for Differences
          run: |
            git fetch origin develop
            git diff --exit-code origin/develop || echo "Differences found"

        - name: Create Pull Request To Develop
          if: success()
          uses: peter-evans/create-pull-request@v5
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            commit-message: "Auto-generated commit"
            branch: auto-pr-branch-${{ github.sha }}
            base: develop
            title: "Auto-generated PR from ${{ github.sha }}"
            body: |
              This is an auto-generated PR to merge changes from feature branch to develop.