name: Feature Workflow

on:
    push:
        branches: ["feature/**"]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src

            - name: Save build artifacts
              uses: actions/upload-artifact@v2
              with:
                name: Artifacts
                path: |
                  src/**/bin/
                  src/**/obj/
    
    unit_test:
        name: Unit Tests
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Download build artifacts
              uses: actions/download-artifact@v2
              with:
                name: Artifacts

            - name: Run tests
              run: dotnet test --no-build --verbosity normal
              working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests