name: Feature Workflow

on:
    push:
        branches: ["feature/**"]

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup .NET Core
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
            
            - name: Restore dependencies
              run: dotnet restore
              working-directory: src

            - name: Build solution
              run: dotnet build --configuration Release --no-restore
              working-directory: src